### PR TITLE
Updated master

### PR DESCRIPTION
**Pull request by torigrooms**

### CODE REVIEW

**Review by soitgoes — COMMENTED** [review]
Looks like you have nested git directories.  You should only have one .git folder at the root of the project

**Comment by torigrooms** [comment]
How do I fix that?

**Comment by torigrooms** [comment]
Completed.

**Review by soitgoes — COMMENTED** [review]
This looks great.  Nice work!

**Comment by torigrooms** [comment]
That means so much coming from you.  Thanks a lot!

**Pull request closed without merging**
